addons:
  postgresql: "9.4"
services:
  - postgresql
language: ruby
dist: xenial
install:
  - bundle install
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - rake spec
deploy:
  provider: heroku
  api_key:
    secure: "qiHVrGaZIIVQZbz/kccgYYhoAeaVi55r81XdPQuXZmTRvNc2EVsC4XSMkEUV2XkbV+UBp1zGbmZW5I+OEdjQUtPaRZnAs2xhkEqQXYVnWre6hd9cAMVVjimtDlPibGeF/S6MxpGljV6P+MAtIqubkKF2AehU63T2T493WeJn4gs5x10DmCIa9WqzHViG/nxINm6JEeQcNWyXb4L2D+yOJ8XChSFaFZD1lqR8jRVcQYR3OCigBbnajFSv3es/U6chKCHqrT+Dkr+slZjSAPH3uacpccWU+tOb6SiBhj65X5+nFdUkAUPjC9gt6+VC7dSDx0e/D8r6ZBJQaizgJ/wvFfvBl74Ls8NjU6rKnSOGwCUuPFBNUBgH6eldzTUD2IOU63o60wZk10+XsDIFrbIqyXX3asEWlIDmvR+FKnn2XDEYO6ikS3oAIeKvDABeVE9m9v34TOuEA1dgPg4UiRE22cN0DaVFKQb7axIdEjcXYuwbDM+LMw3D/NhFiF9bhHY6vDh+H4EMkjn2wEywi7QvY4PSbBCmKnF5MaNhg0McnLtqxzDyzgCwnDCCquVq8wmCtdcGPasMDvuHBeQzQfV3mUGLcdQKPA9FFyiQW/UDOcQGfHCeZI4FKG8BnilwjY7hPvDhheMNu7e30XxPLEPLhgUKjpN2IWkMPQgKdHC53zE="
  run: "rake db:migrate"
