addons:
  postgresql: "9.4"
services:
  - postgresql
language: ruby
dist: xenial
install:
  - bundle install
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - rake spec
deploy:
  provider: heroku
  api_key:
    secure: "ad136cb7-1f2c-45f2-8d10-0508eeb1be70"
  run: "rake db:migrate"
